package bspkrs.util;

import net.minecraftforge.fml.common.registry.ForgeRegistries;

import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;

public class UniqueNameListGenerator
{
    private static UniqueNameListGenerator instance;

    public static UniqueNameListGenerator instance()
    {
        if (instance == null)
            instance = new UniqueNameListGenerator();

        return instance;
    }

    public void run()
    {
        File listFile = new File(new File(CommonUtils.getConfigDir()), "UniqueNames.txt");

        try
        {
            ArrayList<String> blockList = new ArrayList<String>();
            ArrayList<String> itemList = new ArrayList<String>();

            for (Object obj : ForgeRegistries.BLOCKS.getKeys())
                blockList.add(obj.toString());

            for (Object obj : ForgeRegistries.ITEMS.getKeys())
                itemList.add(obj.toString());

            Collections.sort(blockList);
            Collections.sort(itemList);

            if (listFile.exists())
                listFile.delete();

            listFile.createNewFile();

            PrintWriter out = new PrintWriter(new FileWriter(listFile));

            out.println("# generated by bspkrsCore " + new SimpleDateFormat("yyyyMMdd HH:mm:ss").format(new Date()));
            out.println();
            out.println("**********************************************");
            out.println("*  ####   #       ###    ###   #   #   ####  *");
            out.println("*  #   #  #      #   #  #   #  #  #   #      *");
            out.println("*  ####   #      #   #  #      ###     ###   *");
            out.println("*  #   #  #      #   #  #      #  #       #  *");
            out.println("*  ####   #####   ###    ####  #   #  ####   *");
            out.println("**********************************************");
            out.println();
            out.println();

            for (String s : blockList)
            {
                out.println(s);
            }

            out.println();
            out.println();
            out.println("***************************************");
            out.println("*  #####  #####  #####  #   #   ####  *");
            out.println("*    #      #    #      ## ##  #      *");
            out.println("*    #      #    ###    # # #   ###   *");
            out.println("*    #      #    #      #   #      #  *");
            out.println("*  #####    #    #####  #   #  ####   *");
            out.println("***************************************");
            out.println();
            out.println();

            for (String s : itemList)
            {
                out.println(s);
            }

            out.println();
            out.println();

            out.close();

        }
        catch (Exception exception)
        {
            exception.printStackTrace();
        }
    }
}
